force-app/main/default/objects/Search_request__c/Search_request__c.object-meta.xml
<CustomObject>
    <label>Search request</label>
    <nameField>
        <label>Search request</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Search requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Search_request__c/fields/Fibonacci_Above__c.field-meta.xml
<CustomField>
    <fullName>Fibonacci_Above__c</fullName>
    <label>Fibonacci Above</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Search_request__c/fields/Fibonacci_Below__c.field-meta.xml
<CustomField>
    <fullName>Fibonacci_Below__c</fullName>
    <label>Fibonacci Below</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Search_request__c/fields/Numeric_value__c.field-meta.xml
<CustomField>
    <fullName>Numeric_value__c</fullName>
    <label>Numeric value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FindClosestFibonacciBatchTest.cls
/**
 * Created by Bogdan_Krasun on 16.01.2023.
 */
@IsTest
public with sharing class FindClosestFibonacciBatchTest {
    @IsTest
    private static void test() {
        insert new Search_request__c(Name = 'hello', Numeric_value__c = 532);
        Test.startTest();
        Database.executeBatch(new FindClosestFibonacciBatch());
        Test.stopTest();
        Search_request__c sr = [SELECT Name, Fibonacci_Above__c, Fibonacci_Below__c FROM Search_request__c][0];
        System.assertEquals(377, sr.Fibonacci_Below__c, 'Fibonacci number not correct');
        System.assertEquals(610, sr.Fibonacci_Above__c, 'Fibonacci number not correct');
    }
}